const southParkEpisodes = [
  // season 1
  "Cartman Gets An Anal Probe",
  "Weight Gain 4000",
  "Volcano",
  "Big Gay Al's Gay Boat Ride",
  "An Elephant Makes Love To A Pig",
  "Death",
  "Pinkeye",
  "Starvin' Marvin",
  "Mr. Hankey, the Christmas Poo",
  "Damien",
  "Tom's Rhinoplasty",
  "Mecha-Streisand",
  "Cartman's Mom Is A Dirty Slut",
  // Season 2
  "Terrance and Phillip in Not Without My Anus",
  "Cartman's Mom is Still a Dirty Slut",
  "Chickenlover",
  "Ike's Wee Wee",
  "Conjoined Ferus Lady",
  "The Mexican Staring Frog of Southern Sri Lanka",
  "City on the Edge of Forever",
  "Summer Sucks",
  "Chef's Chocolate Salty Balls",
  "Chickenpox",
  "Roger Ebert Should Lay Off the Fatty Foods",
  "Clubhouses",
  "Cow Days",
  "Chef Aid",
  "Spookyfish",
  "Merry Christmas Charlie Manson!",
  "Gnomes",
  "Prehistoric Ice Man",
  // Season 3
  "Rainforest Shmainforest",
  "Spontaneous Combustion",
  "Succubus",
  "Jakovasaurs",
  "Tweek Vs. Craig",
  "Sexual Harassment Panda",
  "Cat Orgy",
  "Two Guys Naked in a Hot Tub",
  "Jewbilee",
  "Korn's Groovy Pirate Ghost Mystery",
  "Chinpokomon",
  "Hooked on Monkey Fonics",
  "Starvin' Marvin in Space",
  "The Red Badge of Gayness",
  "Mr. Hankey's Christmas Classics",
  "Are you There God? It's Me, Jesus",
  "World Wide Recorder Concert",
  // Season 4
  "Tooth Fairy's Tats 2000",
  "Cartman's Silly Hate Crime 2000",
  "Timmy 2000",
  "Quintuplets 2000",
  "Cartman Joins NAMBLA",
  "Cherokee Hair Tampons",
  "Chef Goes Nanners",
  "Something You Can Do With Your Finger",
  "Do The Handicapped Go To Hell?",
  "Probably",
  "Fourth Grade",
  "Trapper Keeper",
  "Helen Keller! The Musical",
  "Pip",
  "Fat Camp",
  "The Wacky Molestation Adventure",
  "A Very Crappy Christmas",
  // Season 5
  "It Hits The Fan",
  "Cripple Fight!",
  "Super Best Friends",
  "Scott Tenorman Must Die",
  "Terrance and Phillip: Behind the Blow",
  "Cartmanland",
  "Proper Condom Use",
  "Towelie",
  "Osama Bin Laden Has Farty Pants",
  "How to Eat With Your Butt",
  "The Entity",
  "Here Comes The Neighborhood",
  // Emmy Winning Episode Under
  "Kenny Dies",
  "Butters' Very Own Episode",
  // Season 6
  "Jared Has Aides",
  "Asspen",
  "Freak Strike",
  "Fun With Veal",
  "The New Terrance and Phillip Move Trailer",
  "Professor Chaos",
  "The Simpsons Already Did It",
  "Red Hot Catholic Love",
  "Free Hat",
  "Bebe's Boobs Destroy Society",
  "Child Abduction is Not Funny",
  "A Ladder to Heaven",
  "The Return of the Fellowship of the Ring to the Two Towers",
  "The Death Camp of Tolerance",
  "The Biggest Douche in the Universe",
  "My Future Self n' Me",
  "Red Sleigh Down",
  // Season 7
  "Cancelled",
  "Krazy Kripples",
  "Toilet Paper",
  "I'm a Little Bit Country",
  "Fat Butt and Pancake Head",
  "Lil' Crime Stoppers",
  "Red Man's Greed",
  "South Park Is Gay",
  "Christian Rock Hard",
  "Grey Dawn",
  "Casa Bonita",
  "All About Mormons",
  "Butt Out",
  "Raisins",
  "It's Christmas in Canada",
  // Season 8
  "Good Times With Weapons",
  "Up the Down Steroid",
  "The Passion of the Jew",
  "You Got F'd in the A",
  "AWESOM-O",
  "The Jeffersons",
  "Goobacks",
  "Douche and Turd",
  "Something Wall-Mart This Way Comes",
  "Preschool",
  "Quest for Ratings",
  "Stupid Spoiled Whore Video Playset",
  "Cartman's Incredible Gift",
  "Woodland Critter Christmas",
  // Season 9
  "Mr. Garrison's Fancy New Vagina",
  "Die Hippie, Die",
  "Wing",
  "Best Friends Forever",
  "The Losing Edge",
  "The Death of Eric Cartman",
  "Erection Day",
  "Two Days Before the Day After Tomorrow",
  "Marjorine",
  "Follow That Egg",
  "Ginger Kids",
  "Trapped in the Closet",
  "Free Willzyx",
  "Bloody Mary",
  // Season 10
  "The Return of Chef",
  "Smug Alert!",
  "Cartoon Wars Part I",
  "Cartoon Wars Part II",
  "A Million Little Fibers",
  "Manbearpig",
  "Tsst",
  // Emmy Winning Episode Under
  "Make Love, Not Warcraft",
  "Mystery of the Urinal Deuce",
  "Miss Teacher Bangs a Boy",
  "Hell on Earth 2006",
  "Go God Go",
  "Go God Go XII",
  "Stanley's Cup",
  // Season 11
  "With Apologies to Jesse Jackson",
  "Cartman Sucks",
  "Lice Capades",
  "The Snuke",
  "Fantastic Easter Special",
  "D-Yikes!",
  "Night of the Living Homeless",
  "Le Petit Tourette",
  "More Crap",
  "Imaginationland",
  "Imaginationland Episode II",
  "Imaginationland Episode III",
  "Guitar Queer-O",
  "The List",
  // Season 12
  "Tonsil Trouble",
  "Britney's New Look",
  "Major Boobage",
  "Canada On Strike",
  "Eek, A Penis",
  "Over Logging",
  "Super Fun Time",
  // October 8th Episode Under
  "The China Probrem",
  "Breast Cancer Show Ever",
  "Pandemic",
  "Pandemic 2 - The Startling",
  "About Last Night...",
  "Elementary School Musical",
  "The Ungroundable",
  // Season 13
  "The Ring",
  "The Coon",
  // Emmy Winning Episode Under
  "Margaritaville",
  "Eat, Pray, Queef",
  "Fishsticks",
  "Pinewood Derby",
  "Fatbeard",
  "Dead Celebrities",
  "Butters' Bottom Bitch",
  "W.T.F.",
  "Whale Whores",
  "The F Word",
  "Dances With Smurfs",
  "Pee",
  // Season 14
  "Sexual Healing",
  "The Tale of Scrotie McBoogerballs",
  "Medicinal Fried Chicken",
  "You Have 0 Friends",
  "200",
  "201",
  "Crippled Summer",
  "Poor and Stupid",
  "It's A Jersey Thing",
  "Insheeption",
  "Coon 2: Hindsight",
  "Mysterion Rises",
  "Coon Vs. Coon & Friends",
  "Creme Fraiche",
  // Season 15
  "HUMANCENTiPAD",
  "Funnybot",
  "Royal Pudding",
  "T.M.I.",
  "Crack Baby Athletic Association",
  "City Sushi",
  "You're Getting Old",
  "Ass Burgers",
  "The Last of the Meheecans",
  "Bass to Mouth",
  "Broadway Bro Down",
  "1%",
  "A History Channel Thanksgiving",
  "The Poor Kid",
  // Season 16
  "Reverse Cowgirl",
  "Cash For Gold",
  "Faith Hilling",
  "Jewpacabra",
  "Butterballs",
  "I should Have Never Gone Ziplining",
  "Cartman Finds Love",
  "Sarcastaball",
  // Emmy Winning Episode Under
  "Raising The Bar",
  "Insecurity",
  "Going Native",
  "A Nightmare On FaceTime",
  "A Scause For Applause",
  "Obama Wins!",
  // Season 17
  "Let Go, Let Gov",
  "Informative Murder Porn",
  "World War Zimmerman",
  "Goth Kids 3: Dawn of the Posers",
  "Taming Strange",
  "Ginger Cow",
  "Black Friday",
  "A Song of Ass and Fire",
  "Titties and Dragons",
  "The Hobbit",
  // Season 18
  "Go Fund Yourself",
  "Gluten Free Ebola",
  // October 8th Episode Under
  "The Cissy",
  "Handicar",
  "The Magic Bush",
  "Freemium Isn't Free",
  "Grounded Vindaloop",
  "Cock Magic",
  "#REHASH",
  "#HappyHolograms",
  // Season 19
  "Stunning and Brave",
  "Where My Country Gone?",
  "The City Part of Town",
  "You're Not Yelping",
  "Safe Space",
  "Tweek X Craig",
  "Naughty Ninjas",
  "Sponsored Content",
  "Truth and Advertising",
  "PC Principal Final Justice",
  // Season 20
  "Member Berries",
  "Skank Hunt",
  "The Damned",
  "Wieners Out",
  "Douche and a Danish",
  "Fort Collins",
  "Oh, Jeez",
  "Members Only",
  "Not Funny",
  "The End of Serialization As We Know It",
  // Season 21
  "White People Renovating Houses",
  "Put It Down",
  "Holiday Special",
  "Franchise Prequel",
  "Hummels & Heroin",
  "Sons a Witches",
  "Doubling Down",
  "Moss Piglets",
  "SUPER HARD PCness",
  "Splatty Tomato",
  // Season 22
  "Dead Kids",
  "A Boy and a Priest",
  "The Problem with a Poo",
  "Tegridy Farms",
  "The Scoots",
  "Time to Get Cereal",
  "Nobody Got Cereal?",
  "Buddha Box",
  "Unfulfilled",
  "Bike Parade",
  // Season 23
  "Mexican Joker",
  "Band in China",
  "SHOTS!!!",
  "Let Them Eat Goo",
  "Tegridy Farms Halloween Special",
  "Season Finale",
  "Board Girls",
  "Turd Burglars",
  "Basic Cable",
  "Christmas Snow",
  // Season 24
  // Emmy Nominated Episode Under
  "The Pandemic Special",
  "South ParQ Vaccination Special",
  // Season 25
  "Pajama Day",
  "The Big Fix",
  "City People",
  "Back to the Cold War",
  "Help, My Teenager Hates Me!",
  "Credigree Weed St. Patrick's Day Special",
  // Season 26
  "Cupid Ye",
  "The Worldwide Privacy Tour",
  "Japanese Toilet",
  "Deep Learning",
  "DikinBaus Hot Dogs",
  "Spring Break",
];

console.log(southParkEpisodes.length);
function generate() {
  console.log(
    southParkEpisodes[Math.floor(Math.random() * southParkEpisodes.length)]
  );
}

generate()
console.log(southParkEpisodes.indexOf('Cartman\'s Mom Is A Dirty Slut'));